[package]
name = "nixcr"
version = "0.1.0"
authors = ["Tom Hunger <tehunger@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.7"
lru-disk-cache = "0.3.0"
serde = "1.0.101"
serde_json = "1.0.40"
sha2 = "0.8.0"
tar = "0.4.26"
