apiVersion: v1
kind: Service
metadata:
  name: nix-store-gcs-proxy
  labels:
    app: nix-store-gcs-proxy
spec:
  ports:
  - port: 80
    targetPort: 3000
    name: web
  selector:
    app: nix-store-gcs-proxy
